In [8]:
# numpyの読み込み
import numpy as np

# AとBの行列を格納
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 行列の積を計算
array_product= np.dot(A, B)

# 行列の積の計算結果を表示
print(array_product)

# 行列の要素の最大値を求める
array_product.max()


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47